# Generated by Django 4.0.3 on 2022-04-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpp',
            fields=[
                ('salesNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=25)),
                ('projectName', models.CharField(max_length=25)),
                ('contactFirstName', models.CharField(max_length=15)),
                ('contactLastName', models.CharField(max_length=15)),
                ('contactTitle', models.CharField(max_length=25)),
                ('contactPhoneNumber', models.CharField(max_length=10)),
                ('contactEmail', models.CharField(max_length=40)),
                ('projectNarrative', models.TextField()),
                ('projectStreet', models.CharField(max_length=25)),
                ('projectCity', models.CharField(max_length=25)),
                ('projectState', models.CharField(max_length=2)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('salesFilePath', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_opp_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectNumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('archived', models.BooleanField(default=False)),
                ('customerID', models.CharField(max_length=8)),
                ('projectFilePath', models.CharField(max_length=200)),
                ('projectType', models.CharField(max_length=25)),
                ('projectCreationDate', models.DateTimeField(auto_now_add=True)),
                ('projectedCompletionDate', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('salesLink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.salesopp')),
            ],
        ),
    ]
