# Generated by Django 4.0.3 on 2022-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesopp',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
