# Generated by Django 4.0.3 on 2022-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_salesopp_projectzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopp',
            name='projectZip',
            field=models.CharField(max_length=6),
        ),
    ]
