# Generated by Django 4.0.3 on 2022-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_salesopp_projectzip'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesopp',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
