# Generated by Django 4.0.3 on 2022-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_salesopp_submitteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watchList',
            field=models.BooleanField(default=False),
        ),
    ]
