# Generated by Django 4.0.3 on 2022-05-18 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0009_pinnedsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDate', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('salesRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.salesopp')),
            ],
        ),
    ]
