# Generated by Django 4.0.3 on 2022-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Bio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
