# Generated by Django 4.0.3 on 2022-04-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Bio',
            new_name='bio',
        ),
    ]
